###
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json

{
  "username": "Joao",
  "password": "1234"
}

###
POST http://localhost:8080/academics/api/documents/upload HTTP/1.1
Authorization: Bearer <copy the token from the output of the above request>
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="<name>"; filename="<filename>"

< <Path to file, do not use '"'>

--boundary
Content-Disposition: form-data; name="username"

Joao

--boundary

###
GET http://localhost:8080/academics/api/documents/download/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded